export const ACTION_GET_ADVERTS_FOR_LISTING_COUNT = `ACTION_GET_ADVERTS_FOR_LISTING_COUNT`
export const ACTION_GET_ADVERT_FOR_LISTING = `ACTION_GET_ADVERT_FOR_LISTING`
export const ACTION_GET_ADVERT = `ACTION_GET_ADVERT`
export const ACTION_UPLOAD_IMAGE = `ACTION_UPLOAD_IMAGE`
export const ACTION_UPLOAD_ADVERT = `ACTION_UPLOAD_ADVERT`
