export const ACTION_LOGIN = `ACTION_LOGIN`
export const ACTION_ENABLE_WEB3 = `ACTION_ENABLE_WEB3`
export const ACTION_LOGOUT = `ACTION_LOGOUT`
export const ACTION_SET_MAIN_SUBSCRIBERS = `ACTION_SET_MAIN_SUBSCRIBERS`
