export const GETTER_ADVERT_TO_EDIT = `GETTER_ADVERT_TO_EDIT`
export const GETTER_ADVERTS = `GETTER_ADVERTS`
export const GETTER_TOTAL_COUNT = `GETTER_TOTAL_COUNT`
export const GETTER_TOTAL_LAST_INDEX = `GETTER_TOTAL_LAST_INDEX`
